services:
  # AIの学習やデータ処理を行うサービス
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    shm_size: '2gb'  # ★ フリーズ対策のためにこの行を追加
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # commandは、upした時のデフォルト動作。runで上書き可能。
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root --notebook-dir=/app/src

  # Webページをブラウザに表示するためのサービス
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./data:/usr/share/nginx/html/data:ro

# 骨格推定を実行するサービス
  mediapipe:
    build: .
    volumes:
      - ./src:/app/src
      - ./output:/app/output # 骨格データを保存するフォルダ
    devices:
      - "/dev/video0:/dev/video0" # PCのWebカメラをコンテナに接続